version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: badgerherald.com-nginx
    links:
        - wordpress
    ports:
      - 80:80
      - 443:443
    volumes:
      - badgerherald.com-wordpress:/var/www/html 
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./server/log/error.log:/etc/nginx/error.log
    restart: always

  db_node_domain:
    image: mariadb
    volumes:
      - badgerherald.com-mysql:/var/lib/mysql:rw
    restart: always
    env_file:
      - server.env
    container_name: badgerherald.com-mysql

  wordpress:
    depends_on:
      - db_node_domain
    image: wordpress:latest
    expose:
      - 80
    restart: always
    env_file:
      - server.env
    volumes: 
      - badgerherald.com-wordpress:/var/www/html
      - ./server/wp-content:/var/www/html/wp-content/
    environment:
      WORDPRESS_DB_HOST: db_node_domain:3306
    container_name: badgerherald.com-wordpress

volumes: 
  badgerherald.com-mysql:
  badgerherald.com-wordpress:
    
networks:
  default:
    external:
      name: badgerherald.com-network
    